import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GoogleTranslateScripts from "@/components/GoogleTranslateScripts"; // 👈 import the client component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Revital Dental",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistSans.variable}>
        <GoogleTranslateScripts />{" "}
        {/* ✅ Fix: Insert script via client component */}
        <div id="google_translate_element"></div>
        {children}
      </body>
    </html>
  );
}
